services:
  - type: web
    name: ecopulse
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: NEWS_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production 